version: 2
updates:
    - directory: /
      package-ecosystem: github-actions
      schedule:
        interval: daily
    - directory: /
      package-ecosystem: gomod
      schedule:
        interval: daily
    - directory: /
      package-ecosystem: gitsubmodule
      schedule:
        interval: daily
